### ISSUE TITLE
Goal limit

### ISSUE THREAD

**Issue by GregoryMoutote** [NicolasGuruphat/smooth-pomodoro#61]
For 16:9 screen 15" 100% zoom setting on Windows, you need about 1100 goals to get out of the page and make the page scrollable.

![image](https://github.com/NicolasGuruphat/smooth-pomodoro/assets/77150680/ec49a8ea-4508-467e-9afe-d2700b787ae9)

**Comment by NicolasGuruphat** [comment]
Should be fix by putting a limit on the input
